server:
  port: 8092
spring:
  cloud:
    gateway:
      routes:
        - id: home_api
          uri: http://localhost:8093
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
# 自定义属性：普通类型、集合、map等多种类型，参考：https://springdoc.cn/spring-yaml-inject-map/
custom:
  app:
    name: InjectMapFromYAML
    url: http://injectmapfromyaml.dev
    description: How To Inject a map from a YAML File in Spring Boot
  config:
    ips:
      - 10.10.10.10
      - 10.10.10.11
      - 10.10.10.12
      - 10.10.10.13
    filesystem:
      - /dev/root
      - /dev/md2
      - /dev/md4
  users:
    root:
      username: root
      password: rootpass
      alias: admin
    guest:
      username: guest
      password: guestpass