server:
  port: 8093

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.211.110:3306/ylang_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null
#mybatis:
#  # 支持统配符 * 或者 ; 分割
#  #配置枚举类扫描路径，会将路径下的枚举类进行注入
##  typeEnumsPackage: com.kkb.project.domain.enums
#  configuration:
#    map-underscore-to-camel-case: true  #从数据库列名到java实体类的映射使用驼峰式命名
#    auto-mapping-behavior: full  #对所有的 resultMap 都进行自动映射
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #配置控制台打印完整带参数SQL语句
##  mapper-locations: classpath*:mapper/**/*Mapper.xml   #配置mapper.xml的路径
#  mapper-locations: classpath*:com/lew/mapper/**/*Mapper.xml   #配置mapper.xml的路径
#  #MyBaits别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper对应的 XML文件
#  #中可以直接使用类名，而不用使用全限定的类名(即 XML 中调用的时候不用包含包名）
#  type-aliases-package: com.lew.modelJdbcOperationsSessionRepositoryJdbcOperationsSessionRepository
mybatis-plus:
  # 支持统配符 * 或者 ; 分割
#  typeEnumsPackage: com.kkb.project.domain.enums
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/lew/**/*Mapper.xml   #配置mapper.xml的路径
  type-aliases-package: com.lew.gateway.model
#  type-enums-package: com.lew.model.enums
logging:
  level:
    root: info
    com.lew.gateway: debug